name: misid_env
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.10
  - xrootd=5.5.1
  - poetry
  - mamba
  - snakemake
  - pip
  - pip:
  # pip-install packages on available in conda-forge or defaults
    - pidcalib2
    - SciencePlots
